### ISSUE TITLE
error PayloadTooLargeError in express

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-server#52]
Hi, I am sending a post request for creating a ticket with attachment in client-side. the attachments are in base64.

 I have recieved the `PayloadTooLargeError: request entity too large` error in express.

adding the following lines did not work:

```js
const bodyParser = require('body-parser');
core.app.use(bodyParser.json({limit: '50mb'}));
core.app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
```

How can I solve this problem?

**Comment by andersevenrud** [comment]
Have you tried adjusting these options https://github.com/os-js/osjs-server/blob/master/src/config.js#L43 ?

**Comment by mahsashadi** [comment]
> Have you tried adjusting these options https://github.com/os-js/osjs-server/blob/master/src/config.js#L43 ?

Yes, It did not work too.

Here is my client-side code:

**Comment by andersevenrud** [comment]
This seems like a custom API or something ?

**Comment by mahsashadi** [comment]
It is zammad api for creating ticket with attachment https://docs.zammad.org/en/latest/api/ticket.html

**Comment by andersevenrud** [comment]
So you know if this is coming from *their* API or OS.js server ?

**Comment by andersevenrud** [comment]
Also, what does the server-side implementation look like ?

**Comment by mahsashadi** [comment]
> Also, what does the server-side implementation look like ?

```js
    routeAuthenticated('POST', proc.resource('tickets/write'), async (req, res) => {
        console.log('routed')
        try {
          HELPDESK_AUTH_TOKEN = req.session.helpdesk['token'];
          await axios.post(`${HELPDESK_BASE_URL}/api/v1/tickets`, req.body, {
            headers: {
              'Authorization': HELPDESK_AUTH_TOKEN,
              'Content-Type': 'application/json'
            }
          })
            .then(response => {
              res.send(response.data);
            });
        } catch (err) {
          console.log('error')
          res.status((err && err.response && err.response.status) || 500).send(err.response.data);
        }
      });
```
nothing printed by above `console.log()` when `error 413` happened, means this error is not coming from zammad api server and osjs express cause that.

BTW, with small files this function performs correctly.

**Comment by mahsashadi** [comment]
![Screenshot from 2021-06-15 17-06-52](https://user-images.githubusercontent.com/70196035/122054928-5f0c6580-cdfd-11eb-9bd4-25ba93ea164c.png)

**Comment by andersevenrud** [comment]
I've published a new version of this package that adds a new configuration option that should solve your issue.

https://github.com/os-js/osjs-server/commit/b1a6c888843d7de9eb1b4011a3242c4ea056364b

**Comment by mahsashadi** [comment]
Thanks.

It still did not solve my issue! just when I increase the value of `maxBodySize` to `'10000kb'`, It routed to my API and _error 413_ changes to _422 Unprocessable Entity_ .

So I think maybe having such a long base64 string in post body request is not meaningful and attached files should be handled in some other way!

**Comment by andersevenrud** [comment]
I don't think I have any traps in my code that would emit a 422. So that's gotta come from the API you're using :thinking:  That might come from the fact that you're sending `req.body` directly and that it either gets corrupted or not the correct format.

**Comment by mahsashadi** [comment]
> That might come from the fact that you're sending `req.body` directly

I did not understand what do you mean by that! How can I send req.body not in a direct way?

**Comment by andersevenrud** [comment]
Nevermind that. I thought maybe this API used multipart form-data to do inline attachments etc, but I just looked at the documentation again, and it's all JSON.

**Comment by mahsashadi** [comment]
Finally it is solved.

The api with attachments in base64 only works for very small files.
using form-data works for all :+1:  however the api was not documented well !

Thanks a lot.

**Comment by andersevenrud** [comment]
Great!
